version: '3'
 
services:
  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.nginx
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    restart: unless-stopped
    volumes:
      - ./db:/app/db

